import { ServerClient } from 'postmark';

// Initialize Postmark client (will be null if no API key)
const postmarkClient = process.env.POSTMARK_API_KEY
  ? new ServerClient(process.env.POSTMARK_API_KEY)
  : null;

// Default from email (should match your Postmark sender signature)
const DEFAULT_FROM_EMAIL = process.env.EMAIL_FROM || 'noreply@flipops.io';

export interface EmailAttachment {
  name: string;
  content: string; // Base64 encoded content
  contentType: string;
}

export interface SendEmailOptions {
  to: string;
  subject: string;
  htmlBody?: string;
  textBody?: string;
  from?: string;
  replyTo?: string;
  attachments?: EmailAttachment[];
  tag?: string;
}

export interface SendEmailResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

/**
 * Send an email using Postmark
 */
export async function sendEmail(options: SendEmailOptions): Promise<SendEmailResult> {
  const { to, subject, htmlBody, textBody, from, replyTo, attachments, tag } = options;

  // Check if Postmark is configured
  if (!postmarkClient) {
    console.warn('Email not sent: POSTMARK_API_KEY not configured');
    return {
      success: false,
      error: 'Email service not configured. Set POSTMARK_API_KEY environment variable.',
    };
  }

  try {
    const response = await postmarkClient.sendEmail({
      From: from || DEFAULT_FROM_EMAIL,
      To: to,
      Subject: subject,
      HtmlBody: htmlBody,
      TextBody: textBody || 'Please view this email in an HTML-capable email client.',
      ReplyTo: replyTo,
      Tag: tag,
      Attachments: attachments?.map((att) => ({
        Name: att.name,
        Content: att.content,
        ContentType: att.contentType,
        ContentID: null,
      })),
    });

    return {
      success: true,
      messageId: response.MessageID,
    };
  } catch (error) {
    console.error('Failed to send email:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown email error',
    };
  }
}

/**
 * Send an invoice email with PDF attachment
 */
export async function sendInvoiceEmail(options: {
  to: string;
  vendorName: string;
  invoiceNumber: string;
  amount: number;
  dueDate: string;
  projectAddress?: string;
  pdfBuffer: Buffer;
  from?: string;
}): Promise<SendEmailResult> {
  const { to, vendorName, invoiceNumber, amount, dueDate, projectAddress, pdfBuffer, from } = options;

  const formattedAmount = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);

  const formattedDate = new Date(dueDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const htmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f8fafc; }
        .amount { font-size: 24px; font-weight: bold; color: #2563eb; }
        .footer { padding: 20px; text-align: center; color: #666; font-size: 12px; }
        .btn { display: inline-block; padding: 12px 24px; background: #2563eb; color: white; text-decoration: none; border-radius: 4px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Invoice #${invoiceNumber}</h1>
        </div>
        <div class="content">
          <p>Dear ${vendorName},</p>
          <p>Please find attached the invoice for services rendered${projectAddress ? ` at <strong>${projectAddress}</strong>` : ''}.</p>
          <p style="text-align: center;">
            <span class="amount">${formattedAmount}</span><br>
            <small>Due by ${formattedDate}</small>
          </p>
          <p>If you have any questions about this invoice, please don't hesitate to reach out.</p>
          <p>Thank you for your business!</p>
        </div>
        <div class="footer">
          <p>This invoice was generated by FlipOps</p>
        </div>
      </div>
    </body>
    </html>
  `;

  return sendEmail({
    to,
    subject: `Invoice #${invoiceNumber} - ${formattedAmount}`,
    htmlBody,
    from,
    attachments: [{
      name: `invoice-${invoiceNumber}.pdf`,
      content: pdfBuffer.toString('base64'),
      contentType: 'application/pdf',
    }],
    tag: 'invoice',
  });
}

/**
 * Send a contract email with PDF attachment
 */
export async function sendContractEmail(options: {
  to: string;
  recipientName: string;
  contractNumber: string;
  contractType: 'vendor' | 'assignment' | 'purchase';
  propertyAddress: string;
  pdfBuffer: Buffer;
  from?: string;
}): Promise<SendEmailResult> {
  const { to, recipientName, contractNumber, contractType, propertyAddress, pdfBuffer, from } = options;

  const contractTypeLabels = {
    vendor: 'Contractor Service Agreement',
    assignment: 'Contract Assignment Agreement',
    purchase: 'Real Estate Purchase Agreement',
  };

  const htmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f8fafc; }
        .property { background: #e0f2fe; padding: 15px; border-radius: 4px; margin: 15px 0; }
        .footer { padding: 20px; text-align: center; color: #666; font-size: 12px; }
        .important { background: #fef3c7; padding: 15px; border-radius: 4px; margin: 15px 0; border-left: 4px solid #f59e0b; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>${contractTypeLabels[contractType]}</h1>
          <p>Contract #${contractNumber}</p>
        </div>
        <div class="content">
          <p>Dear ${recipientName},</p>
          <p>Please find attached the ${contractTypeLabels[contractType].toLowerCase()} for your review.</p>
          <div class="property">
            <strong>Property:</strong><br>
            ${propertyAddress}
          </div>
          <div class="important">
            <strong>Action Required:</strong> Please review the attached contract carefully. If you agree to the terms, sign and return at your earliest convenience.
          </div>
          <p>If you have any questions or require any changes, please don't hesitate to contact us.</p>
        </div>
        <div class="footer">
          <p>This contract was generated by FlipOps</p>
          <p><small>This is a legally binding document. Please read carefully before signing.</small></p>
        </div>
      </div>
    </body>
    </html>
  `;

  return sendEmail({
    to,
    subject: `${contractTypeLabels[contractType]} - ${propertyAddress}`,
    htmlBody,
    from,
    attachments: [{
      name: `contract-${contractNumber}.pdf`,
      content: pdfBuffer.toString('base64'),
      contentType: 'application/pdf',
    }],
    tag: 'contract',
  });
}
