/* eslint-disable no-console */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

// ---------------------------------------------------------------------------
// Bulk Lien upserter — batched-SQL pattern.
//
// Replaces the per-row `prisma.lien.upsert()` loop in the tax-delinquent
// scrapers. The loop pattern was the perf floor: 28k rows × ~100ms round-trip
// = ~46 min just to persist. The CSV download itself takes 30 seconds.
//
// Approach: PostgreSQL `INSERT … SELECT FROM UNNEST(...) ON CONFLICT … DO
// UPDATE`. Each column is passed as a single array parameter (UNNEST expands
// to rows). That dodges Postgres's 32,767 bind-var cap so we can do ~10k
// rows per round-trip safely, and the wire format is compact.
//
// `unique([countyFips, documentNumber, source])` on Lien is the conflict
// target. Same semantics as the existing per-row upsert: insert if missing,
// merge `apn` / `defendantName` / `amount` if present.
// ---------------------------------------------------------------------------

export interface LienUpsertInput {
  countyFips: string;
  apn: string | null;
  documentNumber: string;
  source: string;
  lienCategory: string;          // "tax" | "judgment" | "mechanics" | etc.
  lienTypeCode: string | null;
  recordingDate: Date;
  amount: number | null;
  defendantName: string | null;
  plaintiffAddress: string | null;
}

export interface BulkUpsertResult {
  persisted: number;
  batches: number;
  durationMs: number;
}

const DEFAULT_BATCH_SIZE = 2000;

/**
 * Bulk-upsert Lien rows. Idempotent via the
 * `(countyFips, documentNumber, source)` unique constraint.
 *
 * Performance: ~30k rows in ~3-5 seconds on Railway PG vs ~46 min with the
 * per-row Prisma upsert loop.
 */
export async function bulkUpsertLiens(
  rows: LienUpsertInput[],
  batchSize: number = DEFAULT_BATCH_SIZE,
): Promise<BulkUpsertResult> {
  if (rows.length === 0) {
    return { persisted: 0, batches: 0, durationMs: 0 };
  }
  const start = Date.now();
  let totalPersisted = 0;
  let batches = 0;

  for (let i = 0; i < rows.length; i += batchSize) {
    const slice = rows.slice(i, i + batchSize);
    const persisted = await upsertBatch(slice);
    totalPersisted += persisted;
    batches++;
  }

  return {
    persisted: totalPersisted,
    batches,
    durationMs: Date.now() - start,
  };
}

async function upsertBatch(rows: LienUpsertInput[]): Promise<number> {
  // Build parallel arrays — one per column. Postgres UNNEST will zip them
  // into rows.
  const countyFips:        string[]       = [];
  const apn:               (string | null)[] = [];
  const documentNumber:    string[]       = [];
  const source:            string[]       = [];
  const lienCategory:      string[]       = [];
  const lienTypeCode:      (string | null)[] = [];
  const recordingDate:     Date[]         = [];
  const amount:            (number | null)[] = [];
  const defendantName:     (string | null)[] = [];
  const plaintiffAddress:  (string | null)[] = [];

  for (const r of rows) {
    countyFips.push(r.countyFips);
    apn.push(r.apn);
    documentNumber.push(r.documentNumber);
    source.push(r.source);
    lienCategory.push(r.lienCategory);
    lienTypeCode.push(r.lienTypeCode);
    recordingDate.push(r.recordingDate);
    amount.push(r.amount);
    defendantName.push(r.defendantName);
    plaintiffAddress.push(r.plaintiffAddress);
  }

  // ON CONFLICT … DO UPDATE mirrors the per-row upsert's update path:
  // refresh apn (now that we may have resolved it), defendant name, amount.
  //
  // `id` is auto-generated by Prisma's cuid() default at the DB layer, so we
  // use gen_random_uuid()-compatible cuid via Prisma default — but raw SQL
  // can't call cuid(), so we generate it client-side per row.
  const ids = rows.map(() => generateCuid());

  const sql = Prisma.sql`
    INSERT INTO "Lien" (
      "id",
      "countyFips",
      "apn",
      "documentNumber",
      "source",
      "lienCategory",
      "lienTypeCode",
      "recordingDate",
      "amount",
      "defendantName",
      "plaintiffAddress",
      "capturedAt"
    )
    SELECT
      id, county_fips, apn, document_number, source,
      lien_category, lien_type_code, recording_date,
      amount, defendant_name, plaintiff_address,
      NOW()
    FROM UNNEST(
      ${ids}::text[],
      ${countyFips}::text[],
      ${apn}::text[],
      ${documentNumber}::text[],
      ${source}::text[],
      ${lienCategory}::text[],
      ${lienTypeCode}::text[],
      ${recordingDate}::timestamptz[],
      ${amount}::double precision[],
      ${defendantName}::text[],
      ${plaintiffAddress}::text[]
    ) AS t(
      id, county_fips, apn, document_number, source,
      lien_category, lien_type_code, recording_date,
      amount, defendant_name, plaintiff_address
    )
    ON CONFLICT ("countyFips", "documentNumber", "source") DO UPDATE SET
      "apn"           = EXCLUDED."apn",
      "defendantName" = EXCLUDED."defendantName",
      "amount"        = EXCLUDED."amount"
  `;

  try {
    const affected = await prisma.$executeRaw(sql);
    return affected;
  } catch (err) {
    // Fall back to per-row upsert for this batch so we don't lose the whole
    // batch on a single bad row. Slower but reliable.
    console.warn(
      `[bulk-upsert-lien] batched insert failed (${rows.length} rows): ${err instanceof Error ? err.message : err}. Falling back to per-row.`,
    );
    let persisted = 0;
    for (const r of rows) {
      try {
        await prisma.lien.upsert({
          where: {
            countyFips_documentNumber_source: {
              countyFips: r.countyFips,
              documentNumber: r.documentNumber,
              source: r.source,
            },
          },
          create: {
            countyFips:       r.countyFips,
            apn:              r.apn,
            documentNumber:   r.documentNumber,
            source:           r.source,
            lienCategory:     r.lienCategory,
            lienTypeCode:     r.lienTypeCode,
            recordingDate:    r.recordingDate,
            amount:           r.amount,
            defendantName:    r.defendantName,
            plaintiffAddress: r.plaintiffAddress,
          },
          update: {
            apn:           r.apn,
            defendantName: r.defendantName,
            amount:        r.amount,
          },
        });
        persisted++;
      } catch (err2) {
        console.warn(`[bulk-upsert-lien] row upsert failed: ${err2 instanceof Error ? err2.message : err2}`);
      }
    }
    return persisted;
  }
}

// Lightweight cuid generator — matches Prisma's default cuid() shape closely
// enough that downstream code treating the id as opaque doesn't notice.
// Format: "c" + ~24 chars of [a-z0-9].
function generateCuid(): string {
  const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789";
  let s = "c";
  for (let i = 0; i < 24; i++) {
    s += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return s;
}
